'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import BreadCrumbs, {
    BreadCrumbItem,
} from '@/components/Common/Breadcrumbs';
import HeroCopywritingEdit from '@/components/DisplayManage/HeroSection/HeroCopyWritingEdit';
import { createHeroSection, HeroSectionApiResponse, UpdateHeroSectionPayload } from '@/services/HeroSectionService';

export default function AddHeroPage() {
    const router = useRouter();
    const [isSaving, setIsSaving] = useState(false);

    // Initial empty data for creating
    const initialData: HeroSectionApiResponse = {
        id: '', // Will be generated by server
        headline: '',
        description: '',
        signature: '',
    };

    const handleSave = async (payload: UpdateHeroSectionPayload) => {
        setIsSaving(true);
        try {
            await createHeroSection(payload);
            router.push('/beranda/display/hero');
            router.refresh();
        } catch (error) {
            console.error("Failed to create hero section:", error);
            alert("Failed to create hero section. Please try again.");
        } finally {
            setIsSaving(false);
        }
    };

    const breadcrumbItems: BreadCrumbItem[] = [
        { name: 'Home', href: '/beranda' },
        { name: 'Hero Section', href: '/beranda/display/hero' },
        { name: 'Add Hero Section', disabled: true },
    ];

    return (
        <div className="space-y-8">
            <BreadCrumbs
                items={breadcrumbItems}
                title="Add Hero Copywriting"
                description="Create a new headline, description, and signature for your hero section."
            />

            <HeroCopywritingEdit
                data={initialData}
                onCancel={() => router.back()}
                onSave={handleSave}
            />

            {isSaving && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 backdrop-blur-sm">
                    <div className="rounded-xl bg-white p-6 shadow-xl">
                        <p className="text-sm font-semibold text-[#7A3E2C]">Saving...</p>
                    </div>
                </div>
            )}
        </div>
    );
}
